version: "3"
services:
  manager:
    build: .
    depends_on:
      - db
    environment:
      CSV_FILENAME: data.csv
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
  db:
    image: postgres
    environment : #data.csv
      POSTGRES_USER: POSTGRES_USER
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: POSTGRES_DB
 