FROM python:latest

# the postgres python client library
RUN pip install psycopg2

# copy contents of manager in app folder
COPY . /app/

# run the package as a script
# i.e. run the __main__.py
CMD ["python", "-m", "app"]
